### ISSUE TITLE
url codée en dur dans script JS dans index.js

### ISSUE THREAD

**Issue by refschool** [Sylvainxiii/Clone-Weetransfert#15]
const url = 'http://localhost/Clone-Weetransfert/src/upload.php';

**Comment by Dan-Vial** [comment]
```JavaScript
const url = `${location.origin}/src/upload.php`;
```
j'ai bien la création du fichier sur le serveur, par contre pas d'e-mail.

* correction de `include('fileZip.php')` dans `upload.php`
```php
include('FileZip.php');
```
* ajout de async / await
```JavaScript
form.addEventListener('submit', async (event) => {
....
await fetch(url, {
....
```
* new error: Connection failed: SQLSTATE[HY000] [14] unable to open database file

**Comment by Dan-Vial** [comment]
https://github.com/Sylvainxiii/Clone-Weetransfert/issues/15#issuecomment-2180003653

**Comment by Dan-Vial** [comment]
chemin de la `DB_DATABASE` ajout `../` dans `bddCrud.php`
```php
     $db = new PDO($_ENV['DB_CONNECTION'] . ':' . '../' . $_ENV['DB_DATABASE']);
```
