### ISSUE TITLE
Soucis URL dans index.js

### ISSUE THREAD

**Issue by Sylvainxiii** [Sylvainxiii/Clone-Weetransfert#20]
Suite aux merge des dernières pull request, la ligne 10 du fichier index.js ne fonctionne pas:

const url = `${location.origin}/src/upload.php`;

l'url n'est pas correct, la variable ${location.origin} ne retourne aucune valeur (testé seulement sur environnement windows).

A corriger ou communiquer si c'est le cas les infos de paramètrage manquantes.

Merci

**Comment by refschool** [comment]
voir cette page pour tes soucis
https://stackoverflow.com/questions/6941533/get-protocol-domain-and-port-from-url
