### ISSUE TITLE
Bug frontend en cas d'un second envoie

### ISSUE THREAD

**Issue by Sylvainxiii** [Sylvainxiii/Clone-Weetransfert#26]
Si l'on désire effectuer un second envoie tout en restant sur la même page, 
1-Le texte du champs fichier ne se rempli pas, mais la pièce jointe est quand même prise en compte pour un envoie correct. Après rechargement de la page, ce bug n'apparait pas.

2-Une fois activé, le bouton 'Send' ne se désactive pas si le champs est modifié et contient par la suite des données nulles.

Ces bug n'entrave pas le fonctionnement de l'application.

**Comment by Johhno** [comment]
Je n'ai pas compris. 
À partir du 2nd envoi, le fichier est toujours pris en compte ?

**Comment by Dan-Vial** [comment]
fixé : 
on place la fonction `resetForm();` avant de `fetch()`

**Comment by refschool** [comment]
résolu après déploiement du tag V0.2
