### ISSUE TITLE
Bug Enter

### ISSUE THREAD

**Issue by Dan-Vial** [Sylvainxiii/Clone-Weetransfert#33]
```js
eMailDom.addEventListener('keydown', (event) => {
    if (event.code === 'Enter' && isEmailValid(eMailDom.value)) {
        eMailListUpdate(event);
    } else if (event.code === 'Enter') {
        eMailDom.reportValidity();
    }
   // active ou désactive le bouton send.
    enableSendBtn();  // bug. commenter la ligne supprime le bug mais le bouton send sera toujours désactiver.
});
```

**Comment by Sylvainxiii** [comment]
Peux tu être un peu plus explicite sur les effet du bug stp?

**Comment by refschool** [comment]
demon côté la petite touche Entrée du pavé numérique marchait mais pas la grande ...
Je pense qu'il est préférable d'utiliser event.keyCode = 13 plutôt que event.key = "Enter"

**Comment by Dan-Vial** [comment]
fixé, on utilise :

* pour les touche `Enter` et `NumpadEnter`

```js 
const evCode = event.code === 'Enter' || event.code === 'NumpadEnter'; 
```

* pour évité l’envoi du formulaire sur une des touches

```js
event.preventDefault();
```

Par-contre il est possible de cela pose un souci accessibilité.
Par-défaut la touche `Enter` est utilisée pour valider le formulaire.
Pour réduire l'effet non souhaiter on désactive uniquement `event Enter` sur le focus `input email destinataire`.

Si on juge que c'est inacceptable, faut revoir la façon de faire ou simplement supprimer la fonctionnalité `Enter`.
